doucherism/urls.py
from django.conf.urls import patterns, include, url
from django.http import HttpResponseRedirect
from django.conf import settings
import blog_post.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', lambda x: HttpResponseRedirect('/blog/douchness')),
    url(r'blog/(?P<category>\w+)/$', blog_post.views.blogs),
    url(r'^register/', blog_post.views.register_user_post),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^login/$', blog_post.views.login_user),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media_files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

blog_post/models.py
from django.db import models
from django.conf import settings

# Create your models here.

"""
Simple model to handle blog posts
"""
class Category(models.Model):

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=50)

class BlogEntry(models.Model):
    
    def __unicode__(self):
        return self.blog_post_name

    blog_post_name = models.CharField(max_length=200)
    blog_post_content = models.CharField(max_length=1024)
    blog_pub_date = models.DateTimeField(auto_now=True)
    blog_post_image = models.ImageField(upload_to = settings.MEDIA_ROOT, default = '/media_files/douche.jpg')
    blog_post_category = models.ForeignKey(Category)

blog_post/forms.py
from django.forms import ModelForm
from blog_post.models import BlogEntry

class BlogPostForm(ModelForm):
    class Meta:
        model = BlogEntry
        fields = ['blog_post_name', 'blog_post_content', 'blog_post_image']

blog_post/views.py
from django.shortcuts import render
from blog_post.models import BlogEntry, Category
from blog_post.forms import BlogPostForm
from django.shortcuts import HttpResponseRedirect, redirect
from time import gmtime, strftime
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login

# Create your views here.
"""
This method will display all user posts (newest first)
"""
def blogs(request, category):
    blog_template = "blogs.html"
    list_all_posts = BlogEntry.objects.filter(blog_post_category__name = category).order_by('-blog_pub_date').values('blog_post_name', 'blog_post_content', 'blog_post_category__name', 'blog_post_image') # List all posts on DB ordered by date (newest first).
    return render(request, blog_template, locals())

"""
We will provide the user with a form to upload a post. 
3 fields are available: post name, post data and the file upload option.
the blog_pub_date is automatically set by DB.
"""
def register_user_post(request):
    register_user_template = "register_post.html"
    if request.method == "POST":
            new_blog_post = BlogPostForm(request.POST, request.FILES)
            if new_blog_post.is_valid():
                new_blog_post.save()
                return HttpResponseRedirect('/')
    else:
        form = BlogPostForm()
    return render(request, register_user_template, locals())

def login_user(request):
    template = "login.html"
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                pass
    else:
        return render(request, template, locals())

doucherism/templates/base.html
<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en"> <![endif]-->
    <!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

        <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width" />
            <title>{{ title }}</title>

            <!-- load CSS -->
            <link rel="stylesheet" href="/static/css/normalize.css" />
            <link rel="stylesheet" href="/static/css/foundation.css" />
            <link rel="stylesheet" href="/static/css/jquery.fancybox.css" />

            <!-- load JS -->
            <script src="/static/js/jquery-1.10.2.min.js"></script>
            <script src="/static/js/jquery.fancybox.pack.js"></script>
            <script src="/static/js/vendor/custom.modernizr.js"></script>


        </head>
        <body>

            <div class="sticky">
                <nav class="top-bar">
                <ul class="title-area">
                    <li class="name">
                    <h1><a href="/">Doucherism </a></h1>
                    </li>
                    <li class="toggle-topbar menu-icon"><a href="/"><span>Menu</span></a>
                    </li>
                </ul>

                <section class="top-bar-section">
                <ul class="left">
                    <li class="divider"></li>
                    <li class="active"><a href="/blog/douchness/">Douchness</a></li>
                    <li class="divider"></li>
                    <li><a href="/blog/uberdouche/">Uberdouchness</a></li>
                    <li class="divider"></li>
                    <li><a href="/blog/ultimate/">Ultimate douchness</a></li>
                    <li class="divider"></li>
                    <li class="has-dropdown"><a href="#">Media</a>
                    <ul class="dropdown">
                        <li><a href="#">Videos</a></li>
                        <li><a href="#">Pictures</a></li>
                    </ul>
                    </li>
                    <li class="divider"></li>
                </ul>

		<ul class="right">
                    <li class="has-dropdown"><a href="#">User menu</a>
			<ul class="dropdown">
			    {% if request.user.is_authenticated %}
                                <li><a href="/logout/">Logout</a></li>
                            {% else %}
                                <li><a href="/login/">Login</a></li>
			    {% endif %}
			</ul>
	            </li>
		</ul>
                </section>

                </nav>
            </div>

            {%block content%} <!-- body content here --> {%endblock %}



            <script>
                document.write('<script src=' +
                    ('__proto__' in {} ? '/static/js/vendor/zepto' : '/static/js/vendor/jquery') +
                    '.js><\/script>')
                </script>

                <script src="/static/js/foundation.min.js"></script>

                <script>
                    $(document).foundation();
                </script>

                <script type="text/javascript">
                    $(document).ready(function() {
                            $(".fancybox").fancybox();
                            });
                </script>

                    </body>
                </html>

doucherism/templates/blogs.html
{% extends "base.html" %}
{% load split_string %}
{% block content %}
<div class="row">
    <div class="large-6 columns">
        {% if list_all_posts %}

        {% for post in list_all_posts %}
        <ul class="pricing-table">
            <li class="title">{{ post.blog_post_name }}</li>
            <li class="bullet-item">
            <a class="fancybox" href="/media_files/{{ post.blog_post_image|img_path_last_value:'/' }}" title="{{ post.blog_post_content }}" >
                <img src="/media_files/{{ post.blog_post_image|img_path_last_value:'/' }}" alt="" />
            </a>
            </li>
            <li class="description">{{ post.blog_post_content}}</li>
        </ul>
        {% endfor %}
        {% endif %}

    </div> 
</div>
{% endblock %}

doucherism/templates/login.html
{% extends "base.html" %}
{% block content %}

<form action="/login/" method="POST">{% csrf_token %}
   <fieldset>
	<legend>Login</legend>

   <div class="row">
	<div class="large-6 columns">
        	<label for="user">Username</label>
		<input name="username" type="text" placeholder="Username">
        </div> <!--large-6 columns -->	
   </div><!-- row -->

   <div class="row">
	<div class="large-6 columns">
        	<label for="pass">Password</label>
		<input name="password" type="password" placeholder="Password">
        </div> <!--large-6 columns -->	
   </div><!-- row -->
   
   <div class="row">
	<div class="large-7 columns large-offset-5">
	       <button class="small button">Login</button>
        </div>
   </div>
   </fieldset>
</form>

{% endblock %}

doucherism/templates/register_post.html
{% extends "base.html" %}

{% block content%}
{% if form %}
<form method="post" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
    <fieldset>
        <legend>Register a new post</legend>
        {{ form.as_p }}
        <div id="preview_image">
            {% comment %} We'll show a small preview of the image here {% endcomment %}
        </div>
        <input type="submit" class="button"></a>
</fieldset>
</form>
{% endif %}

<script>
    // set up variables
    var reader = new FileReader(),
    numFiles = 0,
    imageFiles;

    // use the FileReader to read image i
    function readFile() {
        reader.readAsDataURL(imageFiles[0])
    }

    // define function to be run when the File
    // reader has finished reading the file
    reader.onloadend = function(e) {

        // make an image and append it to the div
        var image = $('<img width="460px" height="385px">').attr('src', e.target.result);
        $(image).appendTo('#preview_image');

        // if there are more files run the file reader again
        if (i < numFiles) {
            i++;
            readFile();
        }
    };

    $('#id_blog_post_image').change(function() {
        $('#preview_image').empty();
        imageFiles = document.getElementById('id_blog_post_image').files
        // get the number of files
        numFiles = imageFiles.length;
        readFile();           
    });
</script>
{% endblock %}